# -*- coding: utf-8 -*-
# vim: ft=yaml
---
# For help on this file's format, see https://kitchen.ci/
driver:
  name: docker
  # name: azurerm
  use_sudo: false
  privileged: true
  run_command: /lib/systemd/systemd

  # name: azurerm
  # subscription_id: "<%= ENV['azure_subscription'] %>" # make sure the environment variable is set
  # location: 'WestEurope'
  # machine_size: 'Standard_D2s_v3'
  # username: "azure"

  # transport:
  # name: winrm
  # elevated: true

platforms:
  - name: windows2012R2-sql2016
    driver:
      image_urn: "MicrosoftSQLServer:SQL2016-WS2012R2:SQLDEV:latest"

  ## SALT `master`
  - name: ubuntu-2004-master-py3
    driver:
      image: saltimages/salt-master-py3:ubuntu-20.04
  - name: centos-8-master-py3
    driver:
      image: saltimages/salt-master-py3:centos-8
  - name: centos-7-master-py3
    driver:
      image: saltimages/salt-master-py3:centos-7
  - name: fedora-33-master-py3
    driver:
      image: saltimages/salt-master-py3:fedora-33
  - name: amazonlinux-2-master-py3
    driver:
      image: saltimages/salt-master-py3:amazonlinux-2

  ## SALT `3002.5`
  - name: ubuntu-2004-3002-5-py3
    driver:
      image: saltimages/salt-3002.5-py3:ubuntu-20.04
  - name: centos-8-3002-5-py3
    driver:
      image: saltimages/salt-3002.5-py3:centos-8
  - name: centos-7-3002-5-py3
    driver:
      image: saltimages/salt-3002.5-py3:centos-7
  - name: fedora-33-3002-5-py3
    driver:
      image: saltimages/salt-3002.5-py3:fedora-33
  - name: amazonlinux-2-3002-5-py3
    driver:
      image: saltimages/salt-3002.5-py3:amazonlinux-2

provisioner:
  name: salt_solo
  deprecations_as_errors: false
  log_level: debug
  salt_install: none
  require_chef: false
  formula: TEMPLATE
  salt_copy_filter:
    - .kitchen
    - .git
  retry_on_exit_code:
    - 20
    - 35
    - 259 # required exit code for powershell 5 to install without a chef client failure
  max_retries: 15
  wait_for_retry: 180
  client_rb:
    exit_status: :enabled

verifier:
  # https://www.inspec.io/
  name: inspec
  sudo: true
  # cli, documentation, html, progress, json, json-min, json-rspec, junit
  reporter:
    - cli

suites:
  - name: default
    provisioner:
      state_top:
        base:
          '*':
            - TEMPLATE._mapdata
            - TEMPLATE
      pillars:
        top.sls:
          base:
            '*':
              - TEMPLATE
              - define_roles
      pillars_from_files:
        TEMPLATE.sls: pillar.example
        define_roles.sls: test/salt/pillar/define_roles.sls
    verifier:
      inspec_tests:
        - path: test/integration/default
    suites:

  - name: winazure
    run_list:
      - recipe[powershell::powershell5]
    attributes:
      powershell:
        installation_reboot_mode: 'delayed_reboot'

